INSERT INTO TB_WALLET
    (ID, ID_USER, VL_AMOUNT, DT_CREATE, DT_UPDATE)
VALUES
    (1, 'aa-bb-cc-xx',100, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (2, 'aa-bb-cc-yy',200, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (3, 'aa-bb-cc-zz',300, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
;

INSERT INTO TB_TRANSACTION
    (ID, ID_USER_SOURCE, ID_USER_TARGET, CD_TRANSACTION, ST_STATUS, VL_AMOUNT, DT_CREATE)
VALUES
    (1, 'aa-bb-cc-xx', 'aa-bb-cc-yy', 'aabbcc', 'SUCCESS', 20, CURRENT_TIMESTAMP),
    (2, 'aa-bb-cc-xx', 'aa-bb-cc-yy', 'xxyyzz', 'SUCCESS', 20, CURRENT_TIMESTAMP),
    (3, 'aa-bb-cc-zz', 'aa-bb-cc-yy', 'ttddss', 'FAIL', 20, CURRENT_TIMESTAMP)
;
