CREATE TABLE TB_WALLET(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_USER VARCHAR(50) NOT NULL,
    VL_AMOUNT NUMERIC NOT NULL, -- TODO: CHECK TYPES
    DT_CREATE TIMESTAMP NOT NULL,
    DT_UPDATE TIMESTAMP,

    UNIQUE (ID_USER)
);
CREATE TABLE TB_TRANSACTION(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_USER_SOURCE VARCHAR(50) NOT NULL,
    ID_USER_TARGET VARCHAR(50) NOT NULL,
    CD_TRANSACTION VARCHAR(100) NOT NULL,
    ST_STATUS VARCHAR(40) NOT NULL,
    VL_AMOUNT NUMERIC NOT NULL,
    DT_CREATE TIMESTAMP NOT NULL,

    FOREIGN KEY (ID_USER_SOURCE) REFERENCES TB_WALLET(ID_USER)
);