CREATE TABLE TB_USER(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_EXTERNAL VARCHAR(50) NOT NULL,
    DS_NAME VARCHAR(100) NOT NULL,
    CD_CFP VARCHAR(11),
    CD_CNPJ VARCHAR(14),
    NM_PROFILE VARCHAR(20) NOT NULL,

    UNIQUE (CD_CFP),
    UNIQUE (CD_CNPJ)
);
CREATE TABLE TB_ACCOUNT(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_USER INT NOT NULL,
    NM_EMAIL VARCHAR(100) NOT NULL,
    VL_PASS INT NOT NULL,

    UNIQUE (NM_EMAIL),

    FOREIGN KEY (ID_USER) REFERENCES tb_user(ID)
);