CREATE TABLE TB_USER(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NM_NOME VARCHAR(50) NOT NULL,
    FL_ENABLE BOOLEAN NOT NULL
);
CREATE TABLE TB_FILE_CONFIG(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    ID_USER INTEGER NOT NULL,
    NM_PATH_FTP VARCHAR(200) NOT NULL,
    NM_FILE_NAME VARCHAR(50) NOT NULL,

    FOREIGN KEY (ID_USER) REFERENCES TB_USER (ID)
);
CREATE TABLE TB_FILE(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    ID_USER INTEGER NOT NULL,
    DT_CREATE DATE NOT NULL,

    FOREIGN KEY (ID_USER) REFERENCES TB_USER (ID)
);
CREATE TABLE TB_SHOPPING_LOG(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    ID_FILE INTEGER NOT NULL,
    DS_PRODUCT VARCHAR(200) NOT NULL,
    VL_AMOUNT DOUBLE NOT NULL,
    DT_ORDER DATETIME NOT NULL,

    FOREIGN KEY (ID_FILE) REFERENCES TB_FILE (ID)
);
