CREATE TABLE tb_user(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_EXTERNAL VARCHAR(50),
    DS_NAME VARCHAR(100)
);
CREATE TABLE tb_account(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NM_EMAIL VARCHAR(100),
    VL_PASS INT
);